# Generated by Django 6.1.1 on 2026-09-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reconnaissance institutionnelle',
                'verbose_name_plural': 'Reconnaissances institutionnelles',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(choices=[('plot', 'Lotissement (parcelle)'), ('building', 'BTP (bâtiment)'), ('globe', 'Import-Export (globe)'), ('truck', 'Transport (camion)'), ('exchange', 'Achats-Ventes (échange)'), ('home', 'Immobilier (maison)'), ('box', 'Négoce (colis)')], default='building', max_length=20)),
                ('accent', models.CharField(choices=[('navy', 'Bleu marine'), ('gold', 'Or')], default='navy', max_length=10)),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Département / Activité',
                'verbose_name_plural': 'Départements / Activités',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label_fr', models.CharField(max_length=200)),
                ('label_en', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('plot', 'Lotissement (parcelle)'), ('building', 'BTP (bâtiment)'), ('globe', 'Import-Export (globe)'), ('truck', 'Transport (camion)'), ('exchange', 'Achats-Ventes (échange)'), ('home', 'Immobilier (maison)'), ('box', 'Négoce (colis)')], default='building', max_length=20)),
                ('accent', models.CharField(choices=[('navy', 'Bleu marine'), ('gold', 'Or')], default='navy', max_length=10)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Photo de la galerie',
                'verbose_name_plural': 'Photos de la galerie',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='KANYEL SARL', max_length=200)),
                ('slogan', models.CharField(default="La lumière de l'Éternel", max_length=200)),
                ('leader_name', models.CharField(default='Konan KANYEL', max_length=200)),
                ('leader_role_fr', models.CharField(default='Président Directeur Général', max_length=200)),
                ('leader_role_en', models.CharField(default='Chief Executive Officer', max_length=200)),
                ('address', models.CharField(default="Sopim, Yamoussoukro, Côte d'Ivoire", max_length=255)),
                ('phone_1', models.CharField(blank=True, max_length=50)),
                ('phone_2', models.CharField(blank=True, max_length=50)),
                ('phone_3', models.CharField(blank=True, max_length=50)),
                ('email_main', models.EmailField(blank=True, max_length=254)),
                ('email_leader', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('hours_fr', models.CharField(default='Lundi – Samedi, sur rendez-vous', max_length=200)),
                ('hours_en', models.CharField(default='Monday – Saturday, by appointment', max_length=200)),
                ('hero_title_fr', models.CharField(default='Bâtisseurs de confiance, partenaires de vos ambitions', max_length=255)),
                ('hero_title_en', models.CharField(default='Trusted builders, partners in your ambitions', max_length=255)),
                ('hero_subtitle_fr', models.TextField(blank=True)),
                ('hero_subtitle_en', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('about_paragraph_1_fr', models.TextField(blank=True)),
                ('about_paragraph_1_en', models.TextField(blank=True)),
                ('about_paragraph_2_fr', models.TextField(blank=True)),
                ('about_paragraph_2_en', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('about_image_caption', models.CharField(blank=True, default="Yamoussoukro, Côte d'Ivoire", max_length=200)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
