# Generated by Django 6.1.1 on 2026-09-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reçu le'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='description_en',
            field=models.TextField(verbose_name='Description (anglais)'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='description_fr',
            field=models.TextField(verbose_name='Description (français)'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Titre (anglais)'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='title_fr',
            field=models.CharField(max_length=255, verbose_name='Titre (français)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='accent',
            field=models.CharField(choices=[('navy', 'Bleu marine'), ('gold', 'Or')], default='navy', max_length=10, verbose_name="Couleur d'accent"),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_en',
            field=models.TextField(verbose_name='Description (anglais)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_fr',
            field=models.TextField(verbose_name='Description (français)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(choices=[('plot', 'Lotissement (parcelle)'), ('building', 'BTP (bâtiment)'), ('globe', 'Import-Export (globe)'), ('truck', 'Transport (camion)'), ('exchange', 'Achats-Ventes (échange)'), ('home', 'Immobilier (maison)'), ('box', 'Négoce (colis)')], default='building', max_length=20, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title_en',
            field=models.CharField(max_length=200, verbose_name='Titre (anglais)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title_fr',
            field=models.CharField(max_length=200, verbose_name='Titre (français)'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='accent',
            field=models.CharField(choices=[('navy', 'Bleu marine'), ('gold', 'Or')], default='navy', max_length=10, verbose_name="Couleur d'accent"),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='icon',
            field=models.CharField(choices=[('plot', 'Lotissement (parcelle)'), ('building', 'BTP (bâtiment)'), ('globe', 'Import-Export (globe)'), ('truck', 'Transport (camion)'), ('exchange', 'Achats-Ventes (échange)'), ('home', 'Immobilier (maison)'), ('box', 'Négoce (colis)')], default='building', max_length=20, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='label_en',
            field=models.CharField(max_length=200, verbose_name='Libellé (anglais)'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='label_fr',
            field=models.CharField(max_length=200, verbose_name='Libellé (français)'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Photo à propos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image_caption',
            field=models.CharField(blank=True, default="Yamoussoukro, Côte d'Ivoire", max_length=200, verbose_name='Légende de la photo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_paragraph_1_en',
            field=models.TextField(blank=True, verbose_name='Paragraphe 1 (anglais)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_paragraph_1_fr',
            field=models.TextField(blank=True, verbose_name='Paragraphe 1 (français)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_paragraph_2_en',
            field=models.TextField(blank=True, verbose_name='Paragraphe 2 (anglais)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_paragraph_2_fr',
            field=models.TextField(blank=True, verbose_name='Paragraphe 2 (français)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default="Sopim, Yamoussoukro, Côte d'Ivoire", max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='KANYEL SARL', max_length=200, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_leader',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail du dirigeant'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_main',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail principal'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Photo de couverture'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_en',
            field=models.TextField(blank=True, verbose_name='Sous-titre (anglais)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle_fr',
            field=models.TextField(blank=True, verbose_name='Sous-titre (français)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_en',
            field=models.CharField(default='Trusted builders, partners in your ambitions', max_length=255, verbose_name='Titre principal (anglais)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_fr',
            field=models.CharField(default='Bâtisseurs de confiance, partenaires de vos ambitions', max_length=255, verbose_name='Titre principal (français)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_en',
            field=models.CharField(default='Monday – Saturday, by appointment', max_length=200, verbose_name='Horaires (anglais)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_fr',
            field=models.CharField(default='Lundi – Samedi, sur rendez-vous', max_length=200, verbose_name='Horaires (français)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='leader_name',
            field=models.CharField(default='Konan KANYEL', max_length=200, verbose_name='Nom du dirigeant'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='leader_role_en',
            field=models.CharField(default='Chief Executive Officer', max_length=200, verbose_name='Fonction (anglais)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='leader_role_fr',
            field=models.CharField(default='Président Directeur Général', max_length=200, verbose_name='Fonction (français)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone 2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone 3'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan',
            field=models.CharField(default="La lumière de l'Éternel", max_length=200, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Site web'),
        ),
    ]
