# Generated by Django 6.1.1 on 2026-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ceo_message_en',
            field=models.TextField(blank=True, verbose_name='Mot du DG (anglais)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ceo_message_fr',
            field=models.TextField(blank=True, verbose_name='Mot du DG (français)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leader_photo',
            field=models.ImageField(blank=True, null=True, upload_to='leader/', verbose_name='Photo du dirigeant'),
        ),
    ]
