# Generated by Django 6.1.1 on 2026-09-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sitesettings_ceo_message_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('category', models.CharField(choices=[('villa', 'Villa'), ('appartement', 'Appartement'), ('terrain', 'Terrain'), ('bureau_commerce', 'Bureau / Commerce'), ('immeuble', 'Immeuble')], default='villa', max_length=20, verbose_name='Catégorie')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (français)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (anglais)')),
                ('description_fr', models.TextField(verbose_name='Description (français)')),
                ('description_en', models.TextField(verbose_name='Description (anglais)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('price', models.CharField(blank=True, help_text='Ex. "25 000 000 FCFA", "350 000 FCFA / mois" ou "Sur demande".', max_length=100, verbose_name='Prix / Loyer')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Photo')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Bien immobilier',
                'verbose_name_plural': 'Biens immobiliers',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='detail_content_en',
            field=models.TextField(blank=True, help_text="Fuller text shown on this trade's dedicated page. Leave blank to reuse the short description.", verbose_name='Contenu détaillé (anglais)'),
        ),
        migrations.AddField(
            model_name='department',
            name='detail_content_fr',
            field=models.TextField(blank=True, help_text='Texte plus complet affiché sur la page dédiée à ce métier. Laisser vide pour réutiliser la description courte.', verbose_name='Contenu détaillé (français)'),
        ),
        migrations.AddField(
            model_name='department',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/', verbose_name='Photo de la page détail'),
        ),
        migrations.AddField(
            model_name='department',
            name='has_property_listing',
            field=models.BooleanField(default=False, help_text="À cocher uniquement pour le département Gestion Immobilière : sa page affichera les biens gérés par l'agence.", verbose_name='Afficher la liste des biens immobiliers'),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=220, verbose_name='Identifiant URL (slug)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='description_en',
            field=models.TextField(verbose_name='Description courte (anglais)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_fr',
            field=models.TextField(verbose_name='Description courte (français)'),
        ),
    ]
