# Generated by Django 6.1.1 on 2026-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_department_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default="Nanan, à côté de l'Hôtel Holidays, Yamoussoukro, Côte d'Ivoire", max_length=255, verbose_name='Adresse'),
        ),
    ]
