# Generated by Django 6.1.1 on 2026-09-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_sitesettings_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Ville')),
                ('photo', models.ImageField(blank=True, help_text='Facultatif. Si absent, les initiales du client seront affichées à la place.', null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('message_fr', models.TextField(verbose_name='Témoignage (français)')),
                ('message_en', models.TextField(verbose_name='Témoignage (anglais)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Témoignage client',
                'verbose_name_plural': 'Témoignages clients',
                'ordering': ['order', 'id'],
            },
        ),
    ]
