# Generated by Django 6.1.1 on 2026-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Avec indicatif pays, ex. +225 07 07 03 07 97. Laisser vide pour masquer le bouton WhatsApp du site.', max_length=50, verbose_name='Numéro WhatsApp'),
        ),
    ]
