# Generated by Django 6.1.1 on 2026-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('label_fr', models.CharField(max_length=200, verbose_name='Libellé (français)')),
                ('label_en', models.CharField(max_length=200, verbose_name='Libellé (anglais)')),
                ('value', models.CharField(help_text='Ex. "120", "500+", "15 ans".', max_length=50, verbose_name='Valeur')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Statistique clé',
                'verbose_name_plural': 'Statistiques clés',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='Incrémenté automatiquement à chaque visite du site (une fois par visiteur et par jour). Modifiable manuellement si besoin.', verbose_name='Nombre de visites'),
        ),
    ]
