# Generated by Django 6.1.1 on 2026-09-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_stat_sitesettings_visit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, help_text='Facultatif. Rend le logo cliquable.', verbose_name='Site web')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['order', 'id'],
            },
        ),
    ]
