# Generated by Django 6.1.1 on 2026-09-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('image', models.ImageField(upload_to='departments/gallery/', verbose_name='Photo')),
                ('caption_fr', models.CharField(blank=True, max_length=200, verbose_name='Légende (français)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Légende (anglais)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.department', verbose_name='Activité')),
            ],
            options={
                'verbose_name': 'Photo de galerie (activité)',
                'verbose_name_plural': 'Photos de galerie (activités)',
                'ordering': ['department', 'order', 'id'],
            },
        ),
    ]
