# Generated by Django 6.1.1 on 2026-09-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_departmentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Intitulé du poste (français)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Intitulé du poste (anglais)')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance / Prestation')], default='cdi', max_length=20, verbose_name='Type de contrat')),
                ('location', models.CharField(default="Yamoussoukro, Côte d'Ivoire", max_length=200, verbose_name='Lieu')),
                ('description_fr', models.TextField(verbose_name='Description du poste (français)')),
                ('description_en', models.TextField(verbose_name='Description du poste (anglais)')),
                ('requirements_fr', models.TextField(blank=True, verbose_name='Profil recherché (français)')),
                ('requirements_en', models.TextField(blank=True, verbose_name='Profil recherché (anglais)')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite de candidature')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
