# Generated by Django 6.1.1 on 2026-09-17 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_joboffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('cv', models.FileField(upload_to='applications/cv/', verbose_name='CV')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='applications/cover_letters/', verbose_name='Lettre de motivation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçue le')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('job', models.ForeignKey(blank=True, help_text='Vide pour une candidature spontanée.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='content.joboffer', verbose_name='Offre concernée')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
