# Generated by Django 6.1.1 on 2026-09-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Téléphone'),
        ),
    ]
