# Generated by Django 6.1.1 on 2026-09-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_address_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Identifiant URL (slug)')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (français)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (anglais)')),
                ('excerpt_fr', models.CharField(blank=True, max_length=300, verbose_name='Résumé (français)')),
                ('excerpt_en', models.CharField(blank=True, max_length=300, verbose_name='Résumé (anglais)')),
                ('content_fr', models.TextField(verbose_name='Contenu (français)')),
                ('content_en', models.TextField(verbose_name='Contenu (anglais)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Photo de couverture')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publié le')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('question_fr', models.CharField(max_length=300, verbose_name='Question (français)')),
                ('question_en', models.CharField(max_length=300, verbose_name='Question (anglais)')),
                ('answer_fr', models.TextField(verbose_name='Réponse (français)')),
                ('answer_en', models.TextField(verbose_name='Réponse (anglais)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('department', models.ForeignKey(blank=True, help_text='Laisser vide pour une question générale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='content.department', verbose_name='Activité concernée')),
            ],
            options={
                'verbose_name': 'Question fréquente',
                'verbose_name_plural': 'Questions fréquentes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('budget', models.CharField(choices=[('lt_5m', 'Moins de 5 000 000 FCFA'), ('5m_20m', '5 000 000 – 20 000 000 FCFA'), ('20m_100m', '20 000 000 – 100 000 000 FCFA'), ('gt_100m', 'Plus de 100 000 000 FCFA'), ('unknown', 'À définir')], default='unknown', max_length=20, verbose_name='Budget estimé')),
                ('timeline', models.CharField(choices=[('urgent', "Urgent (moins d'1 mois)"), ('1_3_months', '1 à 3 mois'), ('3_6_months', '3 à 6 mois'), ('6_plus_months', 'Plus de 6 mois'), ('flexible', 'Flexible')], default='flexible', max_length=20, verbose_name='Délai souhaité')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçue le')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='content.department', verbose_name='Activité concernée')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (français)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (anglais)')),
                ('description_fr', models.TextField(verbose_name='Description (français)')),
                ('description_en', models.TextField(verbose_name='Description (anglais)')),
                ('client_name', models.CharField(blank=True, help_text='Facultatif.', max_length=200, verbose_name='Client')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Terminé le')),
                ('image', models.ImageField(upload_to='realisations/', verbose_name='Photo principale')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations', to='content.department', verbose_name='Activité concernée')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['order', '-completed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RealisationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('image', models.ImageField(upload_to='realisations/gallery/', verbose_name='Photo')),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.realisation', verbose_name='Réalisation')),
            ],
            options={
                'verbose_name': 'Photo de réalisation',
                'verbose_name_plural': 'Photos de réalisation',
                'ordering': ['realisation', 'order', 'id'],
            },
        ),
    ]
