# Generated by Django 6.1.1 on 2026-09-17 22:49

import content.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_article_faq_quoterequest_realisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', validators=[content.validators.validate_image_size], verbose_name='Photo de couverture'),
        ),
        migrations.AlterField(
            model_name='department',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/', validators=[content.validators.validate_image_size], verbose_name='Photo de la page détail'),
        ),
        migrations.AlterField(
            model_name='departmentimage',
            name='image',
            field=models.ImageField(upload_to='departments/gallery/', validators=[content.validators.validate_image_size], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[content.validators.validate_image_size], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='applications/cover_letters/', validators=[content.validators.validate_document_size, django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Lettre de motivation'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(upload_to='applications/cv/', validators=[content.validators.validate_document_size, django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/', validators=[content.validators.validate_image_size], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='properties/', validators=[content.validators.validate_image_size], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='image',
            field=models.ImageField(upload_to='realisations/', validators=[content.validators.validate_image_size], verbose_name='Photo principale'),
        ),
        migrations.AlterField(
            model_name='realisationimage',
            name='image',
            field=models.ImageField(upload_to='realisations/gallery/', validators=[content.validators.validate_image_size], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', validators=[content.validators.validate_image_size], verbose_name='Photo à propos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', validators=[content.validators.validate_image_size], verbose_name='Photo de couverture'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='leader_photo',
            field=models.ImageField(blank=True, null=True, upload_to='leader/', validators=[content.validators.validate_image_size], verbose_name='Photo du dirigeant'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Facultatif. Si absent, les initiales du client seront affichées à la place.', null=True, upload_to='testimonials/', validators=[content.validators.validate_image_size], verbose_name='Photo'),
        ),
    ]
