# Generated by Django 6.1.1 on 2026-09-18 08:19

import content.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_article_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Visites')),
            ],
            options={
                'verbose_name': 'Journal de visites',
                'verbose_name_plural': 'Journal de visites',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('full', 'Accès complet'), ('reception', 'Accueil (messages, candidatures, devis uniquement)')], default='full', max_length=20, verbose_name='Rôle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil administrateur',
                'verbose_name_plural': 'Profils administrateurs',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=10, verbose_name='Action')),
                ('resource', models.CharField(help_text='Ex. "departments", "job-applications".', max_length=100, verbose_name='Ressource')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Élément concerné')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée du journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('image', models.ImageField(upload_to='properties/gallery/', validators=[content.validators.validate_image_size], verbose_name='Photo')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.property', verbose_name='Bien')),
            ],
            options={
                'verbose_name': 'Photo de bien immobilier',
                'verbose_name_plural': 'Photos de biens immobiliers',
                'ordering': ['property', 'order', 'id'],
            },
        ),
    ]
