# Generated by Django 6.1.1 on 2026-09-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_visitlog_adminprofile_auditlogentry_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='has_property_listing',
            field=models.BooleanField(default=False, help_text="À cocher uniquement pour le département Achat/Vente et Location : sa page affichera les biens gérés par l'agence.", verbose_name='Afficher la liste des biens immobiliers'),
        ),
    ]
