# Generated by Django 6.1.1 on 2026-09-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_alter_department_has_property_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(choices=[('plot', 'Lotissement (parcelle)'), ('building', 'BTP & VRD (bâtiment)'), ('globe', 'Import-Export (globe)'), ('truck', 'Transport (camion)'), ('exchange', 'Achats-Ventes (échange)'), ('home', 'Immobilier (maison)'), ('box', 'Négoce (colis)')], default='building', max_length=20, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='icon',
            field=models.CharField(choices=[('plot', 'Lotissement (parcelle)'), ('building', 'BTP & VRD (bâtiment)'), ('globe', 'Import-Export (globe)'), ('truck', 'Transport (camion)'), ('exchange', 'Achats-Ventes (échange)'), ('home', 'Immobilier (maison)'), ('box', 'Négoce (colis)')], default='building', max_length=20, verbose_name='Icône'),
        ),
    ]
