# Generated by Django 6.1.1 on 2026-10-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_alter_department_icon_alter_galleryitem_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçue le')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to='content.property', verbose_name='Bien concerné')),
            ],
            options={
                'verbose_name': 'Demande de visite',
                'verbose_name_plural': 'Demandes de visite',
                'ordering': ['-created_at'],
            },
        ),
    ]
